[all:vars]
# CRITICAL: Vagrant VMs always use the user 'vagrant', not 'vboxuser'
ansible_user=vagrant
ansible_python_interpreter=/usr/bin/python3

# This tells Ansible to ignore "Are you sure?" prompts
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[k8s_nodes]
vm1 ansible_host=192.168.56.119 ansible_ssh_private_key_file=../vagrant/.vagrant/machines/vm1/virtualbox/private_key
vm2 ansible_host=192.168.56.120 ansible_ssh_private_key_file=../vagrant/.vagrant/machines/vm2/virtualbox/private_key

[ue_node]
vm3 ansible_host=192.168.56.118 ansible_ssh_private_key_file=../vagrant/.vagrant/machines/vm3/virtualbox/private_key